<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Select printers</title>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    @include('layouts/usersidebar')
    <style>
        #printer {
            margin: 5rem;
        }
    </style>
</head>

@php
    use App\Models\Softwareuser;
    use Illuminate\Support\Facades\DB;

    $userid = Session('softwareuser');
    $adminid = Softwareuser::Where('id', $userid)
        ->pluck('admin_id')
        ->first();
    $adminroles = DB::table('adminusers')
    ->leftJoin('module_roles', 'adminusers.id', '=', 'module_roles.user_id')
    ->where('user_id', $adminid)
    ->get();
@endphp

<body>
    <div id="content">
        @if ($adminroles->contains('module_id', '30'))
        @include('navbar.billingdesknavbar')
    @else
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" id="sidebarCollapse" class="btn navbar-btn">
                    <i class="glyphicon glyphicon-chevron-left"></i>
                    <span></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/dashboard">Back</a></li>
                </ul>
            </div>
        </div>
    </nav>
        @endif

        <div id="printer">
            <!-- <h1>How to directly Print ESCPOS Commands without Preview or Printer Dialog</h1> -->
            <label class="checkbox">
                <input type="checkbox" id="useDefaultPrinter" /> <strong>Use default printer</strong> or...
            </label>
            <div id="loadPrinters">
                <br />
                WebClientPrint can detect the installed printers in your machine.
                <br /> <br />
                <input type="button" onclick="javascript:jsWebClientPrint.getPrinters();" value="Load installed printers..." />

                <br /><br />
            </div>
            <div id="installedPrinters" style="visibility:hidden">
                <br />
                <label for="installedPrinterName">Select an installed Printer:</label>
                <select name="installedPrinterName" id="installedPrinterName"></select>
            </div>

            <br /><br />
            <input type="button" style="font-size:18px" onclick="javascript:jsWebClientPrint.print('useDefaultPrinter=' + $('#useDefaultPrinter').attr('checked') + '&printerName=' + $('#installedPrinterName').val());" value="Print Receipt" class="btn btn-primary" />
        </div>

    </div>
</body>

</html>

<script type="text/javascript">
    var wcppGetPrintersTimeout_ms = 60000; //60 sec
    var wcppGetPrintersTimeoutStep_ms = 500; //0.5 sec

    function wcpGetPrintersOnSuccess() {
        // Display client installed printers
        if (arguments[0].length > 0) {
            var p = arguments[0].split("|");
            var options = '';
            for (var i = 0; i < p.length; i++) {
                options += '<option>' + p[i] + '</option>';
            }
            $('#installedPrinters').css('visibility', 'visible');
            $('#installedPrinterName').html(options);
            $('#installedPrinterName').focus();
            $('#loadPrinters').hide();
        } else {
            alert("No printers are installed in your system.");
        }
    }

    function wcpGetPrintersOnFailure() {
        // Do something if printers cannot be got from the client
        alert("No printers are installed in your system.");
    }
</script>


{!!

// Register the WebClientPrint script code
// The $wcpScript was generated by PrintESCPOSController@index

$wcpScript;

!!}
