<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>printers</title>
    @include('layouts/usersidebar')
</head>

@php
    use App\Models\Softwareuser;
    use Illuminate\Support\Facades\DB;

    $userid = Session('softwareuser');
    $adminid = Softwareuser::Where('id', $userid)
        ->pluck('admin_id')
        ->first();
    $adminroles = DB::table('adminusers')
    ->leftJoin('module_roles', 'adminusers.id', '=', 'module_roles.user_id')
    ->where('user_id', $adminid)
    ->get();
@endphp

<body>
    <div id="content">
        @if ($adminroles->contains('module_id', '30'))
        @include('navbar.billingdesknavbar')
    @else
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" id="sidebarCollapse" class="btn navbar-btn">
                    <i class="glyphicon glyphicon-chevron-left"></i>
                    <span></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/dashboard">Back</a></li>
                </ul>
            </div>
        </div>
    </nav>
        @endif

        <div id="msgInProgress">

            <h3>Detecting WCPP utility at client side...</h3>
            <h3>Please wait a few seconds...</h3>
            <br />
        </div>
        <div id="msgInstallWCPP" style="display:none;">
            <h3>#1 Install WebClientPrint Processor (WCPP)!</h3>
            <p>
                <strong>WCPP is a native app (without any dependencies!)</strong> that handles all print jobs
                generated by the <strong>WebClientPrint for PHP component</strong> at the server side. The WCPP
                is in charge of the whole printing process and can be
                installed on <strong>Windows, Linux, Mac & Raspberry Pi!</strong>
            </p>
            <p>
                <a href="//www.neodynamic.com/downloads/wcpp/" target="_blank">Download and Install WCPP from Neodynamic website</a><br />
            </p>
            <h3>#2 After installing WCPP...</h3>
            <p>
                <a href="{{ route('printESCPOS', $trans) }}">You can go and test the printing page...</a>
            </p>

        </div>
    </div>
</body>

</html>

<script type="text/javascript">
    var wcppPingTimeout_ms = 60000; //60 sec
    var wcppPingTimeoutStep_ms = 500; //0.5 sec

    function wcppDetectOnSuccess() {
        // WCPP utility is installed at the client side
        // redirect to WebClientPrint sample page

        // get WCPP version
        var wcppVer = arguments[0];
        if (wcppVer.substring(0, 1) == "6")
            window.location.href = "{{ route('printESCPOS', $trans) }}";
        else //force to install WCPP v6.0
            wcppDetectOnFailure();
    }

    function wcppDetectOnFailure() {
        // It seems WCPP is not installed at the client side
        // ask the user to install it
        $('#msgInProgress').hide();
        $('#msgInstallWCPP').show();
    }
</script>


{!!

// Register the WCPP Detection script code
// The $wcpScript was generated by HomeController@index

$wcppScript;

!!}
